// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person/person.proto

package com.ing.ipa.person;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:person.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 orgId = 2;</code>
   */
  long getOrgId();

  /**
   * <code>string firstName = 3;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 4;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 4;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string resume = 5;</code>
   */
  java.lang.String getResume();
  /**
   * <code>string resume = 5;</code>
   */
  com.google.protobuf.ByteString
      getResumeBytes();

  /**
   * <code>double salary = 6;</code>
   */
  double getSalary();
}
