// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person/person.proto

package com.ing.ipa.person;

/**
 * Protobuf type {@code person.PersonGetResponse}
 */
public  final class PersonGetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:person.PersonGetResponse)
    PersonGetResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersonGetResponse.newBuilder() to construct.
  private PersonGetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonGetResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PersonGetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.ing.ipa.person.Person.Builder subBuilder = null;
            if (person_ != null) {
              subBuilder = person_.toBuilder();
            }
            person_ = input.readMessage(com.ing.ipa.person.Person.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(person_);
              person_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ing.ipa.person.PersonOuterClass.internal_static_person_PersonGetResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ing.ipa.person.PersonOuterClass.internal_static_person_PersonGetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ing.ipa.person.PersonGetResponse.class, com.ing.ipa.person.PersonGetResponse.Builder.class);
  }

  public static final int PERSON_FIELD_NUMBER = 1;
  private com.ing.ipa.person.Person person_;
  /**
   * <code>.person.Person person = 1;</code>
   */
  public boolean hasPerson() {
    return person_ != null;
  }
  /**
   * <code>.person.Person person = 1;</code>
   */
  public com.ing.ipa.person.Person getPerson() {
    return person_ == null ? com.ing.ipa.person.Person.getDefaultInstance() : person_;
  }
  /**
   * <code>.person.Person person = 1;</code>
   */
  public com.ing.ipa.person.PersonOrBuilder getPersonOrBuilder() {
    return getPerson();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (person_ != null) {
      output.writeMessage(1, getPerson());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (person_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPerson());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ing.ipa.person.PersonGetResponse)) {
      return super.equals(obj);
    }
    com.ing.ipa.person.PersonGetResponse other = (com.ing.ipa.person.PersonGetResponse) obj;

    boolean result = true;
    result = result && (hasPerson() == other.hasPerson());
    if (hasPerson()) {
      result = result && getPerson()
          .equals(other.getPerson());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPerson()) {
      hash = (37 * hash) + PERSON_FIELD_NUMBER;
      hash = (53 * hash) + getPerson().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ing.ipa.person.PersonGetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ing.ipa.person.PersonGetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ing.ipa.person.PersonGetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ing.ipa.person.PersonGetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ing.ipa.person.PersonGetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ing.ipa.person.PersonGetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ing.ipa.person.PersonGetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ing.ipa.person.PersonGetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ing.ipa.person.PersonGetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ing.ipa.person.PersonGetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ing.ipa.person.PersonGetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ing.ipa.person.PersonGetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ing.ipa.person.PersonGetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code person.PersonGetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:person.PersonGetResponse)
      com.ing.ipa.person.PersonGetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ing.ipa.person.PersonOuterClass.internal_static_person_PersonGetResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ing.ipa.person.PersonOuterClass.internal_static_person_PersonGetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ing.ipa.person.PersonGetResponse.class, com.ing.ipa.person.PersonGetResponse.Builder.class);
    }

    // Construct using com.ing.ipa.person.PersonGetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (personBuilder_ == null) {
        person_ = null;
      } else {
        person_ = null;
        personBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ing.ipa.person.PersonOuterClass.internal_static_person_PersonGetResponse_descriptor;
    }

    public com.ing.ipa.person.PersonGetResponse getDefaultInstanceForType() {
      return com.ing.ipa.person.PersonGetResponse.getDefaultInstance();
    }

    public com.ing.ipa.person.PersonGetResponse build() {
      com.ing.ipa.person.PersonGetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.ing.ipa.person.PersonGetResponse buildPartial() {
      com.ing.ipa.person.PersonGetResponse result = new com.ing.ipa.person.PersonGetResponse(this);
      if (personBuilder_ == null) {
        result.person_ = person_;
      } else {
        result.person_ = personBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ing.ipa.person.PersonGetResponse) {
        return mergeFrom((com.ing.ipa.person.PersonGetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ing.ipa.person.PersonGetResponse other) {
      if (other == com.ing.ipa.person.PersonGetResponse.getDefaultInstance()) return this;
      if (other.hasPerson()) {
        mergePerson(other.getPerson());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ing.ipa.person.PersonGetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ing.ipa.person.PersonGetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.ing.ipa.person.Person person_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ing.ipa.person.Person, com.ing.ipa.person.Person.Builder, com.ing.ipa.person.PersonOrBuilder> personBuilder_;
    /**
     * <code>.person.Person person = 1;</code>
     */
    public boolean hasPerson() {
      return personBuilder_ != null || person_ != null;
    }
    /**
     * <code>.person.Person person = 1;</code>
     */
    public com.ing.ipa.person.Person getPerson() {
      if (personBuilder_ == null) {
        return person_ == null ? com.ing.ipa.person.Person.getDefaultInstance() : person_;
      } else {
        return personBuilder_.getMessage();
      }
    }
    /**
     * <code>.person.Person person = 1;</code>
     */
    public Builder setPerson(com.ing.ipa.person.Person value) {
      if (personBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        person_ = value;
        onChanged();
      } else {
        personBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.person.Person person = 1;</code>
     */
    public Builder setPerson(
        com.ing.ipa.person.Person.Builder builderForValue) {
      if (personBuilder_ == null) {
        person_ = builderForValue.build();
        onChanged();
      } else {
        personBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.person.Person person = 1;</code>
     */
    public Builder mergePerson(com.ing.ipa.person.Person value) {
      if (personBuilder_ == null) {
        if (person_ != null) {
          person_ =
            com.ing.ipa.person.Person.newBuilder(person_).mergeFrom(value).buildPartial();
        } else {
          person_ = value;
        }
        onChanged();
      } else {
        personBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.person.Person person = 1;</code>
     */
    public Builder clearPerson() {
      if (personBuilder_ == null) {
        person_ = null;
        onChanged();
      } else {
        person_ = null;
        personBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.person.Person person = 1;</code>
     */
    public com.ing.ipa.person.Person.Builder getPersonBuilder() {
      
      onChanged();
      return getPersonFieldBuilder().getBuilder();
    }
    /**
     * <code>.person.Person person = 1;</code>
     */
    public com.ing.ipa.person.PersonOrBuilder getPersonOrBuilder() {
      if (personBuilder_ != null) {
        return personBuilder_.getMessageOrBuilder();
      } else {
        return person_ == null ?
            com.ing.ipa.person.Person.getDefaultInstance() : person_;
      }
    }
    /**
     * <code>.person.Person person = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ing.ipa.person.Person, com.ing.ipa.person.Person.Builder, com.ing.ipa.person.PersonOrBuilder> 
        getPersonFieldBuilder() {
      if (personBuilder_ == null) {
        personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ing.ipa.person.Person, com.ing.ipa.person.Person.Builder, com.ing.ipa.person.PersonOrBuilder>(
                getPerson(),
                getParentForChildren(),
                isClean());
        person_ = null;
      }
      return personBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:person.PersonGetResponse)
  }

  // @@protoc_insertion_point(class_scope:person.PersonGetResponse)
  private static final com.ing.ipa.person.PersonGetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ing.ipa.person.PersonGetResponse();
  }

  public static com.ing.ipa.person.PersonGetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonGetResponse>
      PARSER = new com.google.protobuf.AbstractParser<PersonGetResponse>() {
    public PersonGetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PersonGetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersonGetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonGetResponse> getParserForType() {
    return PARSER;
  }

  public com.ing.ipa.person.PersonGetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

