// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person/person.proto

package com.ing.ipa.person;

public interface PersonDeleteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:person.PersonDeleteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
