// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person/person.proto

package com.ing.ipa.person;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_PersonGetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_PersonGetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_PersonGetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_PersonGetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_PersonSetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_PersonSetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_PersonSetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_PersonSetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_PersonDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_PersonDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_PersonDeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_PersonDeleteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023person/person.proto\022\006person\"h\n\006Person\022" +
      "\n\n\002id\030\001 \001(\003\022\r\n\005orgId\030\002 \001(\003\022\021\n\tfirstName\030" +
      "\003 \001(\t\022\020\n\010lastName\030\004 \001(\t\022\016\n\006resume\030\005 \001(\t\022" +
      "\016\n\006salary\030\006 \001(\001\"%\n\020PersonGetRequest\022\021\n\tf" +
      "irstName\030\001 \001(\t\"3\n\021PersonGetResponse\022\036\n\006p" +
      "erson\030\001 \001(\0132\016.person.Person\"2\n\020PersonSet" +
      "Request\022\036\n\006person\030\001 \001(\0132\016.person.Person\"" +
      "&\n\021PersonSetResponse\022\021\n\tfirstName\030\001 \001(\t\"" +
      "!\n\023PersonDeleteRequest\022\n\n\002id\030\001 \001(\t\"\"\n\024Pe" +
      "rsonDeleteResponse\022\n\n\002id\030\001 \001(\t2\344\001\n\rPerso" +
      "nService\022B\n\tGetPerson\022\030.person.PersonGet" +
      "Request\032\031.person.PersonGetResponse\"\000\022B\n\t" +
      "SetPerson\022\030.person.PersonSetRequest\032\031.pe" +
      "rson.PersonSetResponse\"\000\022K\n\014DeletePerson" +
      "\022\033.person.PersonDeleteRequest\032\034.person.P" +
      "ersonDeleteResponse\"\000B\026\n\022com.ing.ipa.per" +
      "sonP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_person_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_person_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_Person_descriptor,
        new java.lang.String[] { "Id", "OrgId", "FirstName", "LastName", "Resume", "Salary", });
    internal_static_person_PersonGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_person_PersonGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_PersonGetRequest_descriptor,
        new java.lang.String[] { "FirstName", });
    internal_static_person_PersonGetResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_person_PersonGetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_PersonGetResponse_descriptor,
        new java.lang.String[] { "Person", });
    internal_static_person_PersonSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_person_PersonSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_PersonSetRequest_descriptor,
        new java.lang.String[] { "Person", });
    internal_static_person_PersonSetResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_person_PersonSetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_PersonSetResponse_descriptor,
        new java.lang.String[] { "FirstName", });
    internal_static_person_PersonDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_person_PersonDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_PersonDeleteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_person_PersonDeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_person_PersonDeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_PersonDeleteResponse_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
