// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person/person.proto

package com.ing.ipa.person;

public interface PersonGetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:person.PersonGetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.person.Person person = 1;</code>
   */
  boolean hasPerson();
  /**
   * <code>.person.Person person = 1;</code>
   */
  com.ing.ipa.person.Person getPerson();
  /**
   * <code>.person.Person person = 1;</code>
   */
  com.ing.ipa.person.PersonOrBuilder getPersonOrBuilder();
}
